/* Header file automatically generated from Converters.idl */
/*
 * File built with Microsoft(R) MIDLRT Compiler Engine Version 10.00.0231 
 */

#pragma warning( disable: 4049 )  /* more than 64k source lines */

/* verify that the <rpcndr.h> version is high enough to compile this file*/
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 500
#endif

/* verify that the <rpcsal.h> version is high enough to compile this file*/
#ifndef __REQUIRED_RPCSAL_H_VERSION__
#define __REQUIRED_RPCSAL_H_VERSION__ 100
#endif

#include <rpc.h>
#include <rpcndr.h>

#ifndef __RPCNDR_H_VERSION__
#error this stub requires an updated version of <rpcndr.h>
#endif /* __RPCNDR_H_VERSION__ */

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif /*COM_NO_WINDOWS_H*/
#ifndef __Converters_h_h__
#define __Converters_h_h__
#ifndef __Converters_h_p_h__
#define __Converters_h_p_h__


#pragma once

// Ensure that the setting of the /ns_prefix command line switch is consistent for all headers.
// If you get an error from the compiler indicating "warning C4005: 'CHECK_NS_PREFIX_STATE': macro redefinition", this
// indicates that you have included two different headers with different settings for the /ns_prefix MIDL command line switch
#if !defined(DISABLE_NS_PREFIX_CHECKS)
#define CHECK_NS_PREFIX_STATE "always"
#endif // !defined(DISABLE_NS_PREFIX_CHECKS)


#pragma push_macro("MIDL_CONST_ID")
#undef MIDL_CONST_ID
#define MIDL_CONST_ID const __declspec(selectany)


// Header files for imported files
#include "inspectable.h"

#if defined(__cplusplus) && !defined(CINTERFACE)
#if defined(__MIDL_USE_C_ENUM)
#define MIDL_ENUM enum
#else
#define MIDL_ENUM enum class
#endif
/* Forward Declarations */
#ifndef ____x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_FWD_DEFINED__
namespace ABI {
    namespace Microsoft {
        namespace Terminal {
            namespace UI {
                interface IConvertersStatics;
            } /* UI */
        } /* Terminal */
    } /* Microsoft */
} /* ABI */
#define __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics ABI::Microsoft::Terminal::UI::IConvertersStatics

#endif // ____x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_FWD_DEFINED__




/*
 *
 * Interface Microsoft.Terminal.UI.IConvertersStatics
 *
 * Interface is a part of the implementation of type Microsoft.Terminal.UI.Converters
 *
 *
 * The IID for this interface was automatically generated by MIDLRT.
 *
 * Interface IID generation seed: Microsoft.Terminal.UI.IConvertersStatics:HRESULT InvertBoolean(Boolean,Boolean*);HRESULT PercentageToPercentageValue(Double,Double*);HRESULT PercentageValueToPercentage(Double,Double*);HRESULT StringsAreNotEqual(String,String,Boolean*);HRESULT StringNotEmpty(String,Boolean*);HRESULT StringOrEmptyIfPlaceholder(String,String,String*);
 *
 *
 */
#if !defined(____x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_INTERFACE_DEFINED__)
#define ____x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_INTERFACE_DEFINED__
extern const __declspec(selectany) _Null_terminated_ WCHAR InterfaceName_Microsoft_Terminal_UI_IConvertersStatics[] = L"Microsoft.Terminal.UI.IConvertersStatics";
namespace ABI {
    namespace Microsoft {
        namespace Terminal {
            namespace UI {
                /* [uuid("54ba0c0e-a083-5619-9309-2fce36f7d1b3"), version, object, exclusiveto] */
                MIDL_INTERFACE("54ba0c0e-a083-5619-9309-2fce36f7d1b3")
                IConvertersStatics : public IInspectable
                {
                public:
                    virtual HRESULT STDMETHODCALLTYPE InvertBoolean(
                        /* [in] */::boolean value,
                        /* [out, retval] */::boolean * result
                        ) = 0;
                    virtual HRESULT STDMETHODCALLTYPE PercentageToPercentageValue(
                        /* [in] */double value,
                        /* [out, retval] */double * result
                        ) = 0;
                    virtual HRESULT STDMETHODCALLTYPE PercentageValueToPercentage(
                        /* [in] */double value,
                        /* [out, retval] */double * result
                        ) = 0;
                    virtual HRESULT STDMETHODCALLTYPE StringsAreNotEqual(
                        /* [in] */HSTRING expected,
                        /* [in] */HSTRING actual,
                        /* [out, retval] */::boolean * result
                        ) = 0;
                    virtual HRESULT STDMETHODCALLTYPE StringNotEmpty(
                        /* [in] */HSTRING value,
                        /* [out, retval] */::boolean * result
                        ) = 0;
                    virtual HRESULT STDMETHODCALLTYPE StringOrEmptyIfPlaceholder(
                        /* [in] */HSTRING placeholder,
                        /* [in] */HSTRING value,
                        /* [out, retval] */HSTRING * result
                        ) = 0;
                    
                };

                MIDL_CONST_ID IID & IID_IConvertersStatics=__uuidof(IConvertersStatics);
                
            } /* UI */
        } /* Terminal */
    } /* Microsoft */
} /* ABI */

EXTERN_C const IID IID___x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics;
#endif /* !defined(____x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_INTERFACE_DEFINED__) */


/*
 *
 * Class Microsoft.Terminal.UI.Converters
 *
 * RuntimeClass contains static methods.
 *
 * Class Threading Model:  Both Single and Multi Threaded Apartment
 *
 * Class Marshaling Behavior:  Agile - Class is agile
 *
 */
#ifndef RUNTIMECLASS_Microsoft_Terminal_UI_Converters_DEFINED
#define RUNTIMECLASS_Microsoft_Terminal_UI_Converters_DEFINED
extern const __declspec(selectany) _Null_terminated_ WCHAR RuntimeClass_Microsoft_Terminal_UI_Converters[] = L"Microsoft.Terminal.UI.Converters";
#endif


#else // !defined(__cplusplus)
/* Forward Declarations */
#ifndef ____x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_FWD_DEFINED__
typedef interface __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics;

#endif // ____x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_FWD_DEFINED__



/*
 *
 * Interface Microsoft.Terminal.UI.IConvertersStatics
 *
 * Interface is a part of the implementation of type Microsoft.Terminal.UI.Converters
 *
 *
 * The IID for this interface was automatically generated by MIDLRT.
 *
 * Interface IID generation seed: Microsoft.Terminal.UI.IConvertersStatics:HRESULT InvertBoolean(Boolean,Boolean*);HRESULT PercentageToPercentageValue(Double,Double*);HRESULT PercentageValueToPercentage(Double,Double*);HRESULT StringsAreNotEqual(String,String,Boolean*);HRESULT StringNotEmpty(String,Boolean*);HRESULT StringOrEmptyIfPlaceholder(String,String,String*);
 *
 *
 */
#if !defined(____x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_INTERFACE_DEFINED__)
#define ____x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_INTERFACE_DEFINED__
extern const __declspec(selectany) _Null_terminated_ WCHAR InterfaceName_Microsoft_Terminal_UI_IConvertersStatics[] = L"Microsoft.Terminal.UI.IConvertersStatics";
/* [uuid("54ba0c0e-a083-5619-9309-2fce36f7d1b3"), version, object, exclusiveto] */
typedef struct __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStaticsVtbl
{
    BEGIN_INTERFACE
    HRESULT ( STDMETHODCALLTYPE *QueryInterface)(
    __RPC__in __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics * This,
    /* [in] */ __RPC__in REFIID riid,
    /* [annotation][iid_is][out] */
    _COM_Outptr_  void **ppvObject
    );

ULONG ( STDMETHODCALLTYPE *AddRef )(
    __RPC__in __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics * This
    );

ULONG ( STDMETHODCALLTYPE *Release )(
    __RPC__in __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics * This
    );

HRESULT ( STDMETHODCALLTYPE *GetIids )(
    __RPC__in __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics * This,
    /* [out] */ __RPC__out ULONG *iidCount,
    /* [size_is][size_is][out] */ __RPC__deref_out_ecount_full_opt(*iidCount) IID **iids
    );

HRESULT ( STDMETHODCALLTYPE *GetRuntimeClassName )(
    __RPC__in __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics * This,
    /* [out] */ __RPC__deref_out_opt HSTRING *className
    );

HRESULT ( STDMETHODCALLTYPE *GetTrustLevel )(
    __RPC__in __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics * This,
    /* [OUT ] */ __RPC__out TrustLevel *trustLevel
    );
HRESULT ( STDMETHODCALLTYPE *InvertBoolean )(
        __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics * This,
        /* [in] */boolean value,
        /* [out, retval] */boolean * result
        );
    HRESULT ( STDMETHODCALLTYPE *PercentageToPercentageValue )(
        __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics * This,
        /* [in] */double value,
        /* [out, retval] */double * result
        );
    HRESULT ( STDMETHODCALLTYPE *PercentageValueToPercentage )(
        __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics * This,
        /* [in] */double value,
        /* [out, retval] */double * result
        );
    HRESULT ( STDMETHODCALLTYPE *StringsAreNotEqual )(
        __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics * This,
        /* [in] */HSTRING expected,
        /* [in] */HSTRING actual,
        /* [out, retval] */boolean * result
        );
    HRESULT ( STDMETHODCALLTYPE *StringNotEmpty )(
        __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics * This,
        /* [in] */HSTRING value,
        /* [out, retval] */boolean * result
        );
    HRESULT ( STDMETHODCALLTYPE *StringOrEmptyIfPlaceholder )(
        __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics * This,
        /* [in] */HSTRING placeholder,
        /* [in] */HSTRING value,
        /* [out, retval] */HSTRING * result
        );
    END_INTERFACE
    
} __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStaticsVtbl;

interface __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics
{
    CONST_VTBL struct __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStaticsVtbl *lpVtbl;
};

#ifdef COBJMACROS
#define __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_QueryInterface(This,riid,ppvObject) \
( (This)->lpVtbl->QueryInterface(This,riid,ppvObject) )

#define __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_AddRef(This) \
        ( (This)->lpVtbl->AddRef(This) )

#define __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_Release(This) \
        ( (This)->lpVtbl->Release(This) )

#define __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_GetIids(This,iidCount,iids) \
        ( (This)->lpVtbl->GetIids(This,iidCount,iids) )

#define __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_GetRuntimeClassName(This,className) \
        ( (This)->lpVtbl->GetRuntimeClassName(This,className) )

#define __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_GetTrustLevel(This,trustLevel) \
        ( (This)->lpVtbl->GetTrustLevel(This,trustLevel) )

#define __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_InvertBoolean(This,value,result) \
    ( (This)->lpVtbl->InvertBoolean(This,value,result) )

#define __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_PercentageToPercentageValue(This,value,result) \
    ( (This)->lpVtbl->PercentageToPercentageValue(This,value,result) )

#define __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_PercentageValueToPercentage(This,value,result) \
    ( (This)->lpVtbl->PercentageValueToPercentage(This,value,result) )

#define __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_StringsAreNotEqual(This,expected,actual,result) \
    ( (This)->lpVtbl->StringsAreNotEqual(This,expected,actual,result) )

#define __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_StringNotEmpty(This,value,result) \
    ( (This)->lpVtbl->StringNotEmpty(This,value,result) )

#define __x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_StringOrEmptyIfPlaceholder(This,placeholder,value,result) \
    ( (This)->lpVtbl->StringOrEmptyIfPlaceholder(This,placeholder,value,result) )


#endif /* COBJMACROS */


EXTERN_C const IID IID___x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics;
#endif /* !defined(____x_ABI_CMicrosoft_CTerminal_CUI_CIConvertersStatics_INTERFACE_DEFINED__) */


/*
 *
 * Class Microsoft.Terminal.UI.Converters
 *
 * RuntimeClass contains static methods.
 *
 * Class Threading Model:  Both Single and Multi Threaded Apartment
 *
 * Class Marshaling Behavior:  Agile - Class is agile
 *
 */
#ifndef RUNTIMECLASS_Microsoft_Terminal_UI_Converters_DEFINED
#define RUNTIMECLASS_Microsoft_Terminal_UI_Converters_DEFINED
extern const __declspec(selectany) _Null_terminated_ WCHAR RuntimeClass_Microsoft_Terminal_UI_Converters[] = L"Microsoft.Terminal.UI.Converters";
#endif


#endif // defined(__cplusplus)
#pragma pop_macro("MIDL_CONST_ID")
#endif // __Converters_h_p_h__

#endif // __Converters_h_h__
